#version: '3.8'

services:
  # Backend - Laravel
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
    command: sh -c "composer install && php artisan serve --host=0.0.0.0"

  # Frontend - Angular
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app-network
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: ng serve --host 0.0.0.0

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Doq@521Kbxx35
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Nginx (para Laravel)
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./frontend:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: